baseURL = "https://startwords.cdh.princeton.edu/"
title = "Startwords"
theme = "startwords"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableEmoji = true
googleAnalytics = "UA-87887700-8"

[taxonomies]
  author = "authors"
  tag = "tags"

[permalinks]
  issues = "/:sections/:slug/"

[outputFormats]
  [outputFormats.TXT]
    mediaType = "text/plain"

[outputs]
  page = ["HTML", "TXT"]

[menu]
  [[menu.footer]]
    name = "About"
    url = "about/"
    weight = 20

[params]
  dateform        = "January 2, 2006"
  dateformShort   = "January 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  license = "http://creativecommons.org/licenses/by-nc-sa/4.0/"
  license_text = "Creative Commons Attribution Non-commerical Share Alike License"

[markup.goldmark.renderer]
  unsafe = true