baseURL = "https://startwords.cdh.princeton.edu/"
title = "Startwords"
theme = "startwords"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License."
enableEmoji = true
googleAnalytics = "UA-87887700-8"
enableRobotsTXT = true
# enable git info to get last modified times based on git commits
enableGitInfo = true

# disable taxonomies until we are ready to use them and have templates
disableKinds = ["taxonomy", "term", "tag"]
#[taxonomies]
#  author = "authors"
#  tag = "tags"

[permalinks]
  issues = "/:sections/:slug/"

[outputFormats]
  [outputFormats.TXT]
    mediaType = "text/plain"

[outputs]
  page = ["HTML", "TXT"]

[menu]
  [[menu.footer]]
    name = "About"
    url = "about/"
    weight = 20

[params]
  dateform        = "January 2, 2006"
  dateformShort   = "January 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  license = "http://creativecommons.org/licenses/by/4.0/"
  license_text = "Creative Commons Attribution 4.0 International License"
  images = ["social.png"]
  description = "A research periodical irregularly published by the Center for Digital Humanities at Princeton."
  # set ISSN if/when there is one for inclusion in article metadata
  ISSN = ""

[markup.goldmark.renderer]
  unsafe = true