baseURL: 'https://startwords.cdh.princeton.edu/'
title: Startwords
theme: startwords
copyright: >-
  This work is licensed under a Creative Commons Attribution 4.0 International
  License.
enableEmoji: true
googleAnalytics: UA-87887700-8
enableRobotsTXT: true
enableGitInfo: true
timeout: 300s
disableKinds:
  - taxonomy
  - term
  - tag
permalinks:
  issues: '/:sections/:slug/'

outputFormats:
  TXT:
    mediaType: text/plain
outputs:
  home:
    - HTML
    - RSS
    - ATOM
  section:
    - HTML
    - RSS
    - ATOM
  page:
    - HTML
    - TXT

menu:
  footer:
    - name: About
      url: about/
      weight: 20
    - name: Authors
      url: authors/
      weight: 30


Author:
  name: Center for Digital Humanities at Princeton
  email: cdh-info@princeton.edu

params:
  dateform: 'January 2, 2006'
  dateformShort: January 2
  dateformNum: '2006-01-02'
  dateformNumTime: '2006-01-02 15:04 -0700'
  license: 'http://creativecommons.org/licenses/by/4.0/'
  license_text: Creative Commons Attribution 4.0 International License
  images:
    - social.png
  description: >-
    A research periodical irregularly published by the Center for Digital
    Humanities at Princeton.
  ISSN: 2694-2658
  googleSiteVerification: pS2kpksxg6JeC90IvA8BHVsFuK_6b7J_vARVLqqu7ck

defaultContentLang: en

languages:
  en:
    languageName: English
    weight: 1
    params:
      available_in: Available in English
  es:
    languageName: Español
    weight: 2
    params:
      license_text: Atribución 4.0 Internacional (CC BY 4.0)
      description: >-
        Una publicación periódica de investigación publicada irregularmente por
        el Centro de Humanidades Digitales de Princeton.
      available_in: Disponible en Español
    menu:
      footer:
        - name: Acerca de
          url: /es/acerca-de/
          weight: 20
        - name: Authors
          url: authors/
          weight: 30


markup:
  goldmark:
    renderer:
      unsafe: true

security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
      - ^babel$
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*
