name = "startwords"
description = "Theme for the Startwords research periodical."
tags = ["journal", "research", "periodical"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Center for Digital Humanities @ Princeton"
  homepage = "https://cdh.princeton.edu/"
