name: ci

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.1'
        extended: true 
    
    - name: build site
      run: hugo --minify
