name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.1'
        extended: true

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install npm dependencies
      run: npm ci

    - name: build site
      run: hugo --minify
