name: github pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.67.1'
        extended: true

    - name: build site
      run: hugo --minify

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
      with:
        emptyCommits: false
